openapi: "3.0.0"
info:
  version: "0.0.1"
  title: Todos

servers:
  - url: http://localhost:8000/api/v1

paths:
  /todos:
    get:
      responses:
        "200":
          description: Todo collection
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoCollection'

    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTodo'
      responses:
        "201":
          description: Todo created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'

components:
  schemas:
    TodoCollection:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Todo'

    Todo:
      type: object
      required:
        - id
        - title
      properties:
        id:
          type: integer
          description: A unique identifier for the todo
          example: 4
        title:
          type: string
          description: Title of the todo
          example: Fold laundry

    NewTodo:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          description: Title of the todo
          example: Fold laundry
